### PR TITLE
Basler acA1300 cameras

### PR DESCRIPTION
**Pull request by bhill-slac**
Added xml and generated files for two Basler acA1300 cameras.
Also updated an old AVT Manta G146B.

### CODE REVIEW

**Comment by thomascobb** [comment]
For the AVT Mantas, I was trying to keep one template file for all cameras, as it made support a bit easier. I had to add versioned extra templates for later firmwares because some of the parameters changed name. Do you need any of the extra features for your G046 and G146, or could you use the standard templates? For the Basler I don't have an opinion as I don't know the camera very well.

**Comment by bhill-slac** [comment]
I'd previously developed a deployment pattern for our EDT framegrabber cameras where each camera model had five files per camera.
$MODEL.env macros for dimensions and such
$MODEL.db for db records
$MODEL.edl for it's edm panel,
and 3 cfg files for freeRun, PulseWidth, and ExtTrig operation.
I was just following the same pattern here.
I can see in the long run there could be a lot of duplicates for models 
which return the same xml.
What if I were to rework this commit to share a common firmware specific root for
the xml, template, and edm screens, and move the model specific env file
to a models directory, where I'd create soft links or some type of system 
to map the model to the appropriate firmware specific file set?

**Comment by thomascobb** [comment]
That sounds like it would work

**Comment by thomascobb** [comment]
This repo is deprecated in favour of https://github.com/areaDetector/ADAravis . Please raise an issue on that repo if this is still an issue.

**Pull request closed without merging**
