### PR TITLE
aravis-5 branch merge into master

### PR DESCRIPTION
**Pull request by MarkRivers**
I have tested the aravis-5 branch with:
- GigE camera (Point Grey BlackFlyS)
- 10GigE camera (Point Grey Oryx)
- USB-3 camera (Point Grey Grasshopper 3)

They are all working OK, though the performance of the 10GigE needs improvement.  

I think this branch is ready to be merged into master. 

Once that is done we should try to merge Michael Davidsaver's changes for camera re-connects.

### CODE REVIEW

**Comment by thomascobb** [comment]
@LeeHudsonDLS will be pulling down these changes, testing them internally on RHEL7, then merging Michael's changes

**Comment by MarkRivers** [comment]
This pull request has been pending for almost 3 months.  Has @LeeHudsonDLS made progress on merging this?

**Comment by LeeHudsonDLS** [comment]
I've tested this and it appears to be fine, i've only had to make modification to dls specific files. Should we merge and do a major release?

**Comment by MarkRivers** [comment]
> I've tested this and it appears to be fine, i've only had to make modification to dls specific files. Should we merge and do a major release?

Yes, let's merge first.  Release will need some updates on documentation.

**Pull request merged**
